# Generated by Django 3.0.5 on 2020-04-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_auto_20200409_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
