# Generated by Django 3.0.5 on 2020-05-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0004_auto_20200409_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
