# Generated by Django 3.0.5 on 2020-04-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='animal',
            field=models.ImageField(default=None, upload_to='photos'),
            preserve_default=False,
        ),
    ]
