# Generated by Django 3.0.5 on 2020-04-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_faculty_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='is_canon',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
