# Generated by Django 3.0.5 on 2020-04-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_auto_20200412_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='blood_status',
            field=models.CharField(choices=[('p', 'чистокровный(ая)'), ('h', 'полукровка'), ('m', 'магглорождённый(ая)')], max_length=1),
        ),
    ]
