# Generated by Django 3.0.5 on 2020-04-19 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_auto_20200412_1622'),
        ('forum', '0003_auto_20200419_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.Character'),
        ),
    ]
