# Generated by Django 3.0.5 on 2020-04-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20200419_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
